In [114]:
album_url = 'spotify:album:5IGzOCeKvbUR4q31ZkNz8k'
artist = 'Jul'

In [115]:
username="Kalisto.Willaey"
cid= "31cb8367284144678c38c3d92bf58fb1"
secret="4511d215e2b24898bdcaaa50e4f4693e"

In [116]:
g_id = 'eIPYE9aZaSQXxbjH9C63-7-U4kLpKy3ysmFMgO8NHOFxIqBQNsuwAr322eeKL0yj'
g_secret = 'thIul96PAkpC3_LW-qw1ewUfakWyt7SVWoPKkHOK5HVqnaqwlHC4Yltve-v87R7JVP6mXA9Ka0In09cuvAzodw'
token = 'YVRObE9SY41etLTc3A5LOxvJKl68ouU95eFIw_dS-dBxsDZcdzk7ry5Z2Q8iV6Rc'

In [117]:
from lyricsgenius import Genius
import pandas as pd
import spotipy
from spotipy.oauth2 import SpotifyClientCredentials
from bs4 import BeautifulSoup
import requests

In [118]:
client_credentials_manager = SpotifyClientCredentials(client_id=cid, client_secret=secret)
sp = spotipy.Spotify(client_credentials_manager = client_credentials_manager)

In [119]:
#insert the URI as a string into the function
def get_album_tracks(uri_info):
    uri = []
    track = []
    duration = []
    explicit = []
    track_number = []
    one = sp.album_tracks(uri_info, limit=50, offset=0, market='US')
    df1 = pd.DataFrame(one)
    
    for i, x in df1['items'].items():
        uri.append(x['uri'])
        track.append(x['name'])
        duration.append(x['duration_ms'])
        explicit.append(x['explicit'])
        track_number.append(x['track_number'])
    
    df2 = pd.DataFrame({
    'uri':uri,
    'track':track,
    'duration_ms':duration,
    'explicit':explicit,
    'track_number':track_number})
    
    return df2

In [120]:
#insert output dataframe from the get_album_tracks function
def get_track_info(df, artist):
    danceability = []
    energy = []
    key = []
    loudness = []
    speechiness = []
    acousticness = []
    instrumentalness = []
    liveness = []
    valence = []
    tempo = []
    for i in df['uri']:
        for x in sp.audio_features(tracks=[i]):
            danceability.append(x['danceability'])
            energy.append(x['energy'])
            key.append(x['key'])
            loudness.append(x['loudness'])
            speechiness.append(x['speechiness'])
            acousticness.append(x['acousticness'])
            instrumentalness.append(x['instrumentalness'])
            liveness.append(x['liveness'])
            valence.append(x['valence'])
            tempo.append(x['tempo'])
            
    df2 = pd.DataFrame({
    'danceability':danceability,
    'energy':energy,
    'key':key,
    'loudness':loudness,
    'speechiness':speechiness,
    'acousticness':acousticness,
    'instrumentalness':instrumentalness,
    'liveness':liveness,
    'valence':valence,
    'tempo':tempo,
    'artist':artist})
    
    return df2

In [121]:
def merge_frames(df1, df2):
    df3 = df1.merge(df2, left_index= True, right_index= True)
    return df3

In [122]:
def lyrics_onto_frame(df1, artist_name):
    for i,x in enumerate(df1['track']):
        test = genius.search_song(x, artist_name)
        df1.loc[i, 'lyrics'] = test.lyrics
    return df1

In [123]:
genius = Genius(token)

In [124]:
df1_tracks = get_album_tracks(album_url)
df2_metadata = get_track_info(df1_tracks, artist)
df1 = merge_frames(df1_tracks, df2_metadata)
df = lyrics_onto_frame(df1, artist)

Searching for "Namek" by Jul...
Done.
Searching for "Le 100 le 100" by Jul...
Done.
Searching for "Canette dans les mains" by Jul...
Done.
Searching for "Chocolata" by Jul...
Done.
Searching for "Forbidden" by Jul...
Done.
Searching for "Konami" by Jul...
Done.
Searching for "Grazie la zone" by Jul...
Done.
Searching for "Eh ça va Guy" by Jul...
Done.
Searching for "Héros" by Jul...
Done.
Searching for "Pistolet 45" by Jul...
Done.
Searching for "Cœur blanc" by Jul...
Done.
Searching for "Camouflage" by Jul...
Done.
Searching for "Le Rrrin" by Jul...
Done.
Searching for "C'est pas la mairie" by Jul...
Done.
Searching for "Beuh à la noix de coco" by Jul...
Done.
Searching for "Europa" by Jul...
Done.
Searching for "Perché" by Jul...
Done.
Searching for "Sous tension" by Jul...
Done.
Searching for "La vie de rêve" by Jul...
Done.
Searching for "L'âme abimée" by Jul...
Done.
Searching for "Je le savais" by Jul...
Done.
Searching for "Ils m'ont fait mal" by Jul...
Done.
Searching for "U pistulettu" by Jul...
Done.
Searching for "Bé" by Jul...
Done.
Searching for "J'ai fait le tri" by Jul...
Done.
Searching for "Jhota ou mero" by Jul...
Done.
Searching for "Je deviens loco" by Jul...
Done.
Searching for "Mon cœur pour toi" by Jul...
Done.
Searching for "Première League" by Jul...
Done.
Searching for "N'importe quoi" by Jul...
Done.
Searching for "Aqua dans la Mercedes" by Jul...
Done.
Searching for "Ma rue" by Jul...
Done.
Searching for "Néo" by Jul...
Done.
Searching for "Au bord de la mer" by Jul...
Done.
Searching for "Potion" by Jul...
Done.
Searching for "A.C.C.C" by Jul...
Done.
Searching for "Numéro ten" by Jul...
Done.
Searching for "J'ai vidé le magnum" by Jul...
Done.
Searching for "Sur la selle" by Jul...
Done.
Searching for "J'fais comme je peux" by Jul...
Done.

In [125]:
df.head(5)

,uri,track,duration_ms,explicit,track_number,danceability,energy,key,loudness,speechiness,acousticness,instrumentalness,liveness,valence,tempo,artist,lyrics
0,spotify:track:3HrX1V2CpLmlAu2cGjgrjW,Namek,186306,True,1,0.640,0.541,7,-7.731,0.1620,0.755,0.000445,0.0966,0.765,88.127,Jul,"Namek Lyrics[Paroles de ""Namek"" ft. Omah Lay]\..."
1,spotify:track:6iFjnKoGLAuC24Doa7Z5b4,Le 100 le 100,182586,True,2,0.743,0.793,6,-5.197,0.0657,0.404,0.012900,0.0995,0.884,140.009,Jul,Le 100 le 100 Lyrics[Paroles de “Le 100 le 100...
2,spotify:track:5Wgw0xELVgMedzUXhAxSui,Canette dans les mains,192320,True,3,0.530,0.571,2,-8.004,0.4000,0.809,0.000012,0.1150,0.504,199.560,Jul,Canette dans les mains Lyrics[Paroles de “Cane...
3,spotify:track:27G9K6OFL17tQc14q5EUEA,Chocolata,172840,True,4,0.946,0.704,11,-6.940,0.0798,0.407,0.001390,0.1260,0.593,124.989,Jul,"Chocolata Lyrics[Paroles de ""Chocolata"" ft. El..."
4,spotify:track:5lxIW1YijMLio4srCKxch2,Forbidden,181466,True,5,0.900,0.527,7,-8.316,0.0485,0.160,0.002290,0.0943,0.955,130.016,Jul,"Forbidden Lyrics[Paroles de ""Forbidden""]\n\n[I..."

In [126]:
u = ['artist', 'track', 'lyrics', 'duration_ms']
df = df[u]

In [127]:
df.head(5)

,artist,track,lyrics,duration_ms
0,Jul,Namek,"Namek Lyrics[Paroles de ""Namek"" ft. Omah Lay]\...",186306
1,Jul,Le 100 le 100,Le 100 le 100 Lyrics[Paroles de “Le 100 le 100...,182586
2,Jul,Canette dans les mains,Canette dans les mains Lyrics[Paroles de “Cane...,192320
3,Jul,Chocolata,"Chocolata Lyrics[Paroles de ""Chocolata"" ft. El...",172840
4,Jul,Forbidden,"Forbidden Lyrics[Paroles de ""Forbidden""]\n\n[I...",181466

In [129]:
df.to_csv('data.csv')

In [134]:
print(df.loc[0]['lyrics'])

Namek Lyrics[Paroles de "Namek" ft. Omah Lay]

[Intro : JuL & Omah Lay]
Pou-pou-pou-rou-pou-pou
Pou-pou-pou-rou-pou-wou
Pou-rou-pou-pou-pou-rou
Pou-rou-pou-pou-pou-wou
Pou-rou-pou-pou-pou (pah-pah pah-pah)
Pou-rou-pou-pou-pou-pou (pah-pah pah-pah)
Pou-pou-pou-rou-pou-wou-pou (pah-pah pah-pah)
[Couplet 1 : JuL]
Veste Yamaha, sacoche Chabrand sur le té-c'
Eh, va là-bas, t'es un gros bandeur de tiek
RS4 Break, les pieds sur Terre, la tête sur Namek
Elle est belle ta Patek mais tu vas pas mourir avec
Ils ont dit des choses sur moi, ouais, c'est pas bien mais j'm'en bats les c'
Ça fait les putes avec ses potes, après, ça gonfle les pec' (ses potes, après, ça gonfle les pec')
On a tous des projets, on veut tous la villa
Investir dans la pierre ou dans des vignobles
Mais mon sang, il s'en branle, ouais, que il s'met minable
Et quand il est trop bleu, il s'prend pour un pilote

[Refrain : JuL]
Faut plus qu'on s'voit nous deux si on s'entend pas, pas, pas, pas, pas
J'en ai vu rejoindre les cieux à cause des "Pah, pah, pah, pah, pah"
Le soleil se couche, j'pense à maman, j'pense à papa
J'espère qu'ça parle pas mal quand on s'en va, va, va, va, va
Faut plus qu'on s'voit nous deux si on s'entend pas, pas, pas, pas, pas
J'en ai vu rejoindre les cieux à cause des "Pah, pah, pah, pah, pah"
Le soleil se couche, j'pense à maman, j'pense à papa
J'espère qu'ça parle pas mal quand on s'en va, va, va, va, va

[Couplet 2 : Omah Lay]
All the things they be talking about when I do [?] quibble in the truth
All of the [?] are the [?] flower, cannabis, I think that's my roots
Follow the air for the [?] and I guess [?] yeah but it's my roof
All of the mens are [?] 'cause I'm finding my way to escape
Through this dum-dum-dum (dum-dum-dum dum-dum-dum)
Boom-boom-boom (boom-boom-boom boom-boom-boom)
God knows I have tried with you
My singles don't have bulletproof
Oh-oh I feel it deep down in my spirit
Things I wish for my siblings
Don't know if they miss me
I'm speaking my feelings
God knows I'm [?]
Wah-wah-wah-wah-wah
(Pah-pah-pah-pah)
You might also like[Refrain : JuL & Omah Lay]
Faut plus qu'on s'voit nous deux si on s'entend pas, pas, pas, pas, pas (Pas, pas, pas, pas)
J'en ai vu rejoindre les cieux à cause des "Pah, pah, pah, pah, pah" (Pah, pah, pah, pah)
Le soleil se couche, j'pense à maman, j'pense à papa (Papa, papa)
J'espère qu'ça parle pas mal quand on s'en va, va, va, va, va, va (Pah, pah, pah, pah, pah, pah)
Faut plus qu'on s'voit nous deux si on s'entend pas, pas, pas, pas, pas (Pas, pas, pas, pas, pas, pas)
J'en ai vu rejoindre les cieux à cause des "Pah, pah, pah, pah, pah" (Pah, pah, pah, pah, pah, pah)
Le soleil se couche, j'pense à maman, j'pense à papa (Papa, papa, papa)
J'espère qu'ça parle pas mal quand on s'en va, va, va, va, va, va (Pah, pah, pah)

[Outro : JuL]
Pou-pou-pou-rou-pou-pou
Pou-pou-pou-rou-pou-wou
Pou-rou-pou-pou-pou-rou
Pou-rou-pou-pou-pou-wou
Pou-rou-pou-pou-pou
Pou-rou-pou-pou-pou-pou
Pou-pou-pou-rou-pou-wou-pouEmbed